from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, date, datetime

COMPETITION_CONTRACT = "0x212c61b9b72c95d95bf29cf032f5e5635629aed5"
REGISTRATION_DEADLINE = datetime(2026, 6, 22, 0, 0, tzinfo=UTC)
TRADING_WINDOW_START = date(2026, 6, 22)
TRADING_WINDOW_END = date(2026, 6, 28)

ELIGIBLE_TOKENS = {
    "ETH",
    "USDT",
    "USDC",
    "XRP",
    "TRX",
    "DOGE",
    "ZEC",
    "ADA",
    "LINK",
    "BCH",
    "DAI",
    "TON",
    "USD1",
    "USDE",
    "M",
    "LTC",
    "AVAX",
    "SHIB",
    "XAUT",
    "WLFI",
    "H",
    "DOT",
    "UNI",
    "ASTER",
    "DEXE",
    "USDD",
    "ETC",
    "AAVE",
    "ATOM",
    "U",
    "STABLE",
    "FIL",
    "INJ",
    "币安人生",
    "NIGHT",
    "FET",
    "TUSD",
    "BONK",
    "PENGU",
    "CAKE",
    "SIREN",
    "LUNC",
    "ZRO",
    "KITE",
    "FDUSD",
    "BEAT",
    "PIEVERSE",
    "BTT",
    "NFT",
    "EDGE",
    "FLOKI",
    "LDO",
    "B",
    "FF",
    "PENDLE",
    "NEX",
    "STG",
    "AXS",
    "TWT",
    "HOME",
    "RAY",
    "COMP",
    "GWEI",
    "XCN",
    "GENIUS",
    "XPL",
    "BAT",
    "SKYAI",
    "APE",
    "IP",
    "SFP",
    "TAG",
    "NXPC",
    "AB",
    "SAHARA",
    "1INCH",
    "CHEEMS",
    "BANANAS31",
    "RIVER",
    "MYX",
    "RAVE",
    "SNX",
    "FORM",
    "LAB",
    "HTX",
    "USDF",
    "CTM",
    "BDX",
    "SLX",
    "UB",
    "DUCKY",
    "FRAX",
    "BILL",
    "WFI",
    "KOGE",
    "ALE",
    "FRXUSD",
    "GOMINING",
    "VCNT",
    "GUA",
    "DUSD",
    "SMILEK",
    "0G",
    "BEAM",
    "MY",
    "SOON",
    "REAL",
    "Q",
    "AIOZ",
    "ZIG",
    "YFI",
    "TAC",
    "LISUSD",
    "CYS",
    "ZAMA",
    "TRIA",
    "HUMA",
    "PLUME",
    "ZIL",
    "XPR",
    "ZETA",
    "BABYDOGE",
    "NILA",
    "ROSE",
    "VELO",
    "UAI",
    "BRETT",
    "OPEN",
    "BSB",
    "TOSHI",
    "BAS",
    "ACH",
    "AXL",
    "LUR",
    "ELF",
    "KAVA",
    "APR",
    "IRYS",
    "EURI",
    "XUSD",
    "BARD",
    "DUSK",
    "SUSHI",
    "PEAQ",
    "COAI",
    "BDCA",
    "XAUM",
}


@dataclass(frozen=True)
class CompetitionState:
    now: datetime
    registration_deadline: datetime
    trading_window_start: date
    trading_window_end: date
    is_registration_open: bool
    is_trading_window: bool


def competition_state(now: datetime | None = None) -> CompetitionState:
    resolved_now = now or datetime.now(UTC)
    today = resolved_now.date()
    return CompetitionState(
        now=resolved_now,
        registration_deadline=REGISTRATION_DEADLINE,
        trading_window_start=TRADING_WINDOW_START,
        trading_window_end=TRADING_WINDOW_END,
        is_registration_open=resolved_now < REGISTRATION_DEADLINE,
        is_trading_window=TRADING_WINDOW_START <= today <= TRADING_WINDOW_END,
    )

